export default strings = {
  title: 'The Breaking Bad',
  favourites: 'Favourites',
  app_name: 'Track App',
  details: 'Details',
  potrayed: 'Potrayed',
  occupation: 'Occupation',
  other_characters:'Other characters',
  appeard_in: 'Appeard in',
  please_turn_on: 'Please turn ON your data or wifi',
  no_internet_connection: 'No Internet Connection',
  please_check_your_internet: 'Please check your internet connection',
  try_again: 'Try Again',
  no_movie_to_show: 'No movie to show.',
  no_fav_to_show: 'No favourite character to show.',
  search_by: 'Search',
};
